/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-11-19 04:20:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import model.Product;
import model.Category;
import java.util.List;
import model.Category;

public final class category_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/templates/includes/footer.jsp", Long.valueOf(1729433651533L));
    _jspx_dependants.put("/templates/includes/navbar.jsp", Long.valueOf(1731988887070L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.Product");
    _jspx_imports_classes.add("model.Category");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Chức năng: Hiển thị sản phẩm theo danh mục (ví dụ: quần áo nam, nữ, trẻ em).\r\n");
      out.write("    Nội dung: Danh sách sản phẩm thuộc danh mục cụ thể mà người dùng chọn.-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("     <title>Our store</title>\r\n");
      out.write("\r\n");
      out.write("       <!-- Favicon -->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <!-- jQuery -->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-2.0.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("     <!-- Bootstrap4 files -->\r\n");
      out.write("     <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/bootstrap.bundle.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("     <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- Font awesome 5 -->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/fonts/fontawesome/css/all.min.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom style -->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/responsive.css\" rel=\"stylesheet\" media=\"only screen and (max-width: 1200px)\" />\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom javascript -->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/script.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" </head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"section-header\">\r\n");
      out.write("<nav class=\"navbar p-md-0 navbar-expand-sm navbar-light border-bottom\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarTop4\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarTop4\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a href=\"#\" class=\"nav-link\">   English </a>\r\n");
      out.write("\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item dropdown\">\r\n");
      out.write("      <a href=\"#\" class=\"nav-link\"> USD </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("    <li><a href=\"#\" class=\"nav-link\"> <i class=\"fa fa-envelope\"></i> Email </a></li>\r\n");
      out.write("    <li><a href=\"#\" class=\"nav-link\"> <i class=\"fa fa-phone\"></i> Call us </a></li>\r\n");
      out.write("  </ul> <!-- list-inline //  -->\r\n");
      out.write("  </div> <!-- navbar-collapse .// -->\r\n");
      out.write("</div> <!-- container //  -->\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<section class=\"header-main border-bottom\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("  <div class=\"col-lg-2 col-md-3 col-6\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"brand-wrap\">\r\n");
      out.write("                <img class=\"logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/logo.png\" alt=\"Logo\">\r\n");
      out.write("    </a> <!-- brand-wrap.// -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-lg col-sm col-md col-6 flex-grow-0\">\r\n");
      out.write("    <div class=\"category-wrap dropdown d-inline-block float-right\">\r\n");
      out.write("      <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("        <i class=\"fa fa-bars\"></i> All category\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"dropdown-menu\">\r\n");
      out.write("         <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?id=all\">All products</a>\r\n");
      out.write("\r\n");
      out.write("                        ");

                            // Get the list of categories from the request attribute

                                List<Category> categoryList = (List<Category>) application.getAttribute("categoryList");

                            if (categoryList != null) {
                                for (Category category : categoryList) {
                        
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?id=");
      out.print( category.getId() );
      out.write("\">\r\n");
      out.write("                                    ");
      out.print( category.getTitle() );
      out.write("\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        ");

                                }
                            } else {
                        
      out.write("\r\n");
      out.write("                            <li>No categories available.</li>\r\n");
      out.write("                        ");

                            }
                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>  <!-- category-wrap.// -->\r\n");
      out.write("  </div> <!-- col.// -->\r\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?id=all\" class=\"btn btn-outline-primary\">Store</a>\r\n");
      out.write("  <div class=\"col-lg  col-md-6 col-sm-12 col\">\r\n");
      out.write("    <form action=\"search\" class=\"search\" method=\"post\">\r\n");
      out.write("      <div class=\"input-group w-100\">\r\n");
      out.write("          <input type=\"text\" name=\"txt\" class=\"form-control\" style=\"width:60%;\" placeholder=\"Search\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${txtS}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"input-group-append\">\r\n");
      out.write("            <button class=\"btn btn-primary\" type=\"submit\">\r\n");
      out.write("              <i class=\"fa fa-search\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form> <!-- search-wrap .end// -->\r\n");
      out.write("  </div> <!-- col.// -->\r\n");
      out.write("  <div class=\"col-lg-3 col-sm-6 col-8 order-2 order-lg-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-end mb-3 mb-lg-0\">\r\n");
      out.write("          <div class=\"widget-header\">\r\n");
      out.write("            <small class=\"title text-muted\">Welcome guest!</small>\r\n");
      out.write("            <div>\r\n");
      out.write("              <a href=\"templates/login.jsp\">Login</a> <span class=\"dark-transp\"> | </span>\r\n");
      out.write("              <a href=\"templates/register.jsp\"> Register</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"./cart.html\" class=\"widget-header pl-3 ml-3\">\r\n");
      out.write("            <div class=\"icon icon-sm rounded-circle border\"><i class=\"fa fa-shopping-cart\"></i></div>\r\n");
      out.write("            <span class=\"badge badge-pill badge-danger notify\">0</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div> <!-- widgets-wrap.// -->\r\n");
      out.write("      </div> <!-- col.// -->\r\n");
      out.write("</div> <!-- row.// -->\r\n");
      out.write("  </div> <!-- container.// -->\r\n");
      out.write("</section> <!-- header-main .// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header> <!-- section-header.// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ========================= SECTION PAGETOP ========================= -->\r\n");
      out.write("<section class=\"section-pagetop bg\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"title-page\">Our Store</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- ========================= SECTION CONTENT ========================= -->\r\n");
      out.write("<section class=\"section-content padding-y\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <aside class=\"col-md-3\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <article class=\"filter-group\">\r\n");
      out.write("                        <header class=\"card-header\">\r\n");
      out.write("                            <a href=\"#\" data-toggle=\"collapse\" data-target=\"#collapse_1\" aria-expanded=\"true\" class=\"\">\r\n");
      out.write("                                <i class=\"icon-control fa fa-chevron-down\"></i>\r\n");
      out.write("                                <h6 class=\"title\">Categories</h6>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </header>\r\n");
      out.write("                        <div class=\"filter-content collapse show\" id=\"collapse_1\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <ul class=\"list-menu\">\r\n");
      out.write("                                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?id=all\">All products</a></li>\r\n");
      out.write("                                    ");

                                        List<Category> categories = (List<Category>) application.getAttribute("categoryList");
                                       if (categories != null) {
                                            for (Category category : categories) {
                                    
      out.write("\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/category?id=");
      out.print( category.getId() );
      out.write("\">\r\n");
      out.write("                                                ");
      out.print( category.getTitle() );
      out.write("\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    ");

                                            }
                                        } else {
                                    
      out.write("\r\n");
      out.write("                                        <li>No categories available.</li>\r\n");
      out.write("                                    ");

                                        }
                                    
      out.write("\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </article>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Các filter cho sizes và price range có thể giữ nguyên -->\r\n");
      out.write("                    <article class=\"filter-group\">\r\n");
      out.write("                        <header class=\"card-header\">\r\n");
      out.write("                            <a href=\"#\" data-toggle=\"collapse\" data-target=\"#collapse_4\" aria-expanded=\"true\" class=\"\">\r\n");
      out.write("                                <i class=\"icon-control fa fa-chevron-down\"></i>\r\n");
      out.write("                                <h6 class=\"title\">Sizes</h6>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </header>\r\n");
      out.write("                        <div class=\"filter-content collapse show\" id=\"collapse_4\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <label class=\"checkbox-btn\">\r\n");
      out.write("                                    <input type=\"checkbox\">\r\n");
      out.write("                                    <span class=\"btn btn-light\"> XS </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"checkbox-btn\">\r\n");
      out.write("                                    <input type=\"checkbox\">\r\n");
      out.write("                                    <span class=\"btn btn-light\"> SM </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"checkbox-btn\">\r\n");
      out.write("                                    <input type=\"checkbox\">\r\n");
      out.write("                                    <span class=\"btn btn-light\"> LG </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"checkbox-btn\">\r\n");
      out.write("                                    <input type=\"checkbox\">\r\n");
      out.write("                                    <span class=\"btn btn-light\"> XXL </span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <form action=\"filter\" method=\"post\">\r\n");
      out.write("                        <article class=\"filter-group\">\r\n");
      out.write("                            <header class=\"card-header\">\r\n");
      out.write("                                <a href=\"#\" data-toggle=\"collapse\" data-target=\"#collapse_3\" aria-expanded=\"true\" class=\"\">\r\n");
      out.write("                                    <i class=\"icon-control fa fa-chevron-down\"></i>\r\n");
      out.write("                                    <h6 class=\"title\">Price range</h6>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </header>\r\n");
      out.write("                            <div class=\"filter-content collapse show\" id=\"collapse_3\">\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"form-row\">\r\n");
      out.write("                                        <div class=\"form-group col-md-6\">\r\n");
      out.write("                                            <label>Min</label>\r\n");
      out.write("                                            <select name=\"minPrice\" class=\"mr-2 form-control\">\r\n");
      out.write("                                                <option value=\"0\">$0</option>\r\n");
      out.write("                                                <option value=\"50\">$50</option>\r\n");
      out.write("                                                <option value=\"100\">$100</option>\r\n");
      out.write("                                                <option value=\"150\">$150</option>\r\n");
      out.write("                                                <option value=\"200\">$200</option>\r\n");
      out.write("                                                <option value=\"500\">$500</option>\r\n");
      out.write("                                                <option value=\"1000\">$1000</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group text-right col-md-6\">\r\n");
      out.write("                                            <label>Max</label>\r\n");
      out.write("                                            <select name=\"maxPrice\" class=\"mr-2 form-control\">\r\n");
      out.write("                                                <option value=\"50\">$50</option>\r\n");
      out.write("                                                <option value=\"100\">$100</option>\r\n");
      out.write("                                                <option value=\"150\">$150</option>\r\n");
      out.write("                                                <option value=\"200\">$200</option>\r\n");
      out.write("                                                <option value=\"500\">$500</option>\r\n");
      out.write("                                                <option value=\"1000\">$1000</option>\r\n");
      out.write("                                                <option value=\"2000\">$2000+</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-block btn-primary\">Apply</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </article>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <main class=\"col-md-9\">\r\n");
      out.write("                <header class=\"border-bottom mb-4 pb-3\">\r\n");
      out.write("                    <div class=\"form-inline\">\r\n");
      out.write("                        ");

                            // Get the product list from the request
                            List<Product> productList = (List<Product>) request.getAttribute("productList");

                            // Get the count of items
                            int itemCount = (productList != null) ? productList.size() : 0; // Ensure null check to avoid NullPointerException
                        
      out.write("\r\n");
      out.write("                        <span class=\"mr-md-auto\"><b>");
      out.print( itemCount );
      out.write("</b> Items found</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </header>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    ");

                        // If productList is not null, iterate over it and display products
                        if (productList != null) {
                            for (Product product : productList) {
                    
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <figure class=\"card card-product-grid\">\r\n");
      out.write("                            <div class=\"img-wrap\">\r\n");
      out.write("                               <a href=\"./product?id=");
      out.print( product.getId() );
      out.write("\" ><img src=\"");
      out.print( product.getPhoto() );
      out.write("\" alt=\"");
      out.print( product.getName() );
      out.write("\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <figcaption class=\"info-wrap\">\r\n");
      out.write("                                <div class=\"fix-height\">\r\n");
      out.write("                                    <a href=\"./product?id=");
      out.print( product.getId() );
      out.write("\" class=\"title\">");
      out.print( product.getName() );
      out.write("</a>\r\n");
      out.write("                                    <div class=\"price-wrap mt-2\">\r\n");
      out.write("                                        <span class=\"price\">$ ");
      out.print( product.getPrice() );
      out.write("</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-block btn-success\">Add to cart</a>\r\n");
      out.write("                            </figcaption>\r\n");
      out.write("                        </figure>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                            }
                        } else {
                    
      out.write("\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <p>No products found.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <nav class=\"mt-4\" aria-label=\"Page navigation sample\">\r\n");
      out.write("                    <ul class=\"pagination\">\r\n");
      out.write("                        <li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">Previous</a></li>\r\n");
      out.write("                        <li class=\"page-item active\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Next</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </main>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- ========================= FOOTER ========================= -->\r\n");
      out.write("<footer class=\"section-footer border-top\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<section class=\"footer-bottom border-top row\">\r\n");
      out.write("			<div class=\"col-md-2\">\r\n");
      out.write("				<p class=\"text-muted\"> &copy 2019 Company name </p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-8 text-md-center\">\r\n");
      out.write("				<span  class=\"px-2\">info@pixsellz.io</span>\r\n");
      out.write("				<span  class=\"px-2\">+879-332-9375</span>\r\n");
      out.write("				<span  class=\"px-2\">Street name 123, Avanue abc</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-2 text-md-right text-muted\">\r\n");
      out.write("				<i class=\"fab fa-lg fa-cc-visa\"></i>\r\n");
      out.write("				<i class=\"fab fa-lg fa-cc-paypal\"></i>\r\n");
      out.write("				<i class=\"fab fa-lg fa-cc-mastercard\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</div><!-- //container -->\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- ========================= FOOTER END // ========================= --\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
