/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-11-01 12:19:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"max-age=604800\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<title>GreatKart | One of the Biggest Online Shopping Platform</title>\r\n");
      out.write(" <!-- Favicon -->\r\n");
      out.write("       <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("       <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-2.0.0.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap4 files -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/bootstrap.bundle.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("   <!-- Font awesome 5 -->\r\n");
      out.write("       <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/fonts/fontawesome/css/all.min.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("       <!-- Custom style -->\r\n");
      out.write("       <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("       <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/responsive.css\" rel=\"stylesheet\" media=\"only screen and (max-width: 1200px)\" />\r\n");
      out.write("\r\n");
      out.write("       <!-- Custom javascript -->\r\n");
      out.write("       <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/script.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ========================= SECTION CONTENT ========================= -->\r\n");
      out.write("<section class=\"section-content padding-y\">\r\n");
      out.write("\r\n");
      out.write("<!-- ============================ COMPONENT REGISTER   ================================= -->\r\n");
      out.write("	<div class=\"card mx-auto\" style=\"max-width:520px; margin-top:40px;\">\r\n");
      out.write("      <article class=\"card-body\">\r\n");
      out.write("		<header class=\"mb-4\"><h4 class=\"card-title\">Sign up</h4></header>\r\n");
      out.write("		<form action=\"register\">\r\n");
      out.write("				<div class=\"form-row\">\r\n");
      out.write("					<div class=\"col form-group\">\r\n");
      out.write("						<label >First name</label>\r\n");
      out.write("					  	<input name =\"FirstName\" type=\"text\" class=\"form-control\" placeholder=\"\">\r\n");
      out.write("					</div> <!-- form-group end.// -->\r\n");
      out.write("					<div class=\"col form-group\">\r\n");
      out.write("						<label>Last name</label>\r\n");
      out.write("					  	<input name =\"LastName\" type=\"text\" class=\"form-control\" placeholder=\"\">\r\n");
      out.write("					</div> <!-- form-group end.// -->\r\n");
      out.write("				</div> <!-- form-row end.// -->\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label>Email</label>\r\n");
      out.write("					<input name=\"Email\" type=\"email\" class=\"form-control\" placeholder=\"\">\r\n");
      out.write("					<small class=\"form-text text-muted\">We'll never share your email with anyone else.</small>\r\n");
      out.write("				</div> <!-- form-group end.// -->\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("					  <input name=\"gender\" class=\"custom-control-input\" checked=\"\" type=\"radio\" name=\"gender\" value=\"1\">\r\n");
      out.write("					  <span class=\"custom-control-label\"> Male </span>\r\n");
      out.write("					</label>\r\n");
      out.write("					<label class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("					  <input name=\"gender\" class=\"custom-control-input\" type=\"radio\" name=\"gender\" value=\"0\">\r\n");
      out.write("					  <span class=\"custom-control-label\"> Female </span>\r\n");
      out.write("					</label>\r\n");
      out.write("				</div> <!-- form-group end.// -->\r\n");
      out.write("				<div class=\"form-row\">\r\n");
      out.write("					<div class=\"form-group col-md-6\">\r\n");
      out.write("					  <label>Quốc Gia</label>\r\n");
      out.write("					  <input type=\"text\" class=\"form-control\">\r\n");
      out.write("					</div> <!-- form-group end.// -->\r\n");
      out.write("					<div class=\"form-group col-md-6\">\r\n");
      out.write("					  <label>Thành phố / Tỉnh</label>\r\n");
      out.write("					  <select name=\"city\" id=\"inputState\" class=\"form-control\">\r\n");
      out.write("					    <option selected=\"\"> Choose...</option>\r\n");
      out.write("					      <option name=\"city\" value=\"Long An\">Long An</option>\r\n");
      out.write("					      <option name=\"city\" value=\"Bình Định\">Bình Địng</option>\r\n");
      out.write("					      <option name=\"city\" value=\"Quy Nhơn\" >Quy Nhơn</option>\r\n");
      out.write("					      <option name=\"city\" value=\"Quảng Ngãi\">Quảng Ngãi</option>\r\n");
      out.write("					      <option name=\"city\" value=\"Hà Nội\">Hà Nội</option>\r\n");
      out.write("					      <option name=\"city\" value=\"Hồ Chí Minh\">Hồ Chí Minh</option>\r\n");
      out.write("					  </select>\r\n");
      out.write("					</div> <!-- form-group end.// -->\r\n");
      out.write("				</div> <!-- form-row.// -->\r\n");
      out.write("				<div class=\"form-row\">\r\n");
      out.write("					<div class=\"form-group col-md-6\">\r\n");
      out.write("						<label>Create password</label>\r\n");
      out.write("					    <input name=\"password\" class=\"form-control\" type=\"password\">\r\n");
      out.write("					</div> <!-- form-group end.// -->\r\n");
      out.write("					<div class=\"form-group col-md-6\">\r\n");
      out.write("						<label>Repeat password</label>\r\n");
      out.write("					    <input name=\"CheckPassword\" class=\"form-control\" type=\"password\">\r\n");
      out.write("					</div> <!-- form-group end.// -->\r\n");
      out.write("				</div>\r\n");
      out.write("			    <div class=\"form-group\">\r\n");
      out.write("			        <button type=\"submit\" class=\"btn btn-primary btn-block\"> Register  </button>\r\n");
      out.write("			    </div> <!-- form-group// -->\r\n");
      out.write("\r\n");
      out.write("			</form>\r\n");
      out.write("		</article><!-- card-body.// -->\r\n");
      out.write("    </div> <!-- card .// -->\r\n");
      out.write("    <p class=\"text-center mt-4\">Have an account? <a href=\"login.jsp\">Log In</a></p>\r\n");
      out.write("    <br><br>\r\n");
      out.write("<!-- ============================ COMPONENT REGISTER  END.// ================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- ========================= SECTION CONTENT END// ========================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ========================= FOOTER ========================= -->\r\n");
      out.write("<footer class=\"section-footer border-top padding-y\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<p class=\"float-md-right\">\r\n");
      out.write("			&copy Copyright 2019 All rights reserved\r\n");
      out.write("		</p>\r\n");
      out.write("		<p>\r\n");
      out.write("			<a href=\"#\">Terms and conditions</a>\r\n");
      out.write("		</p>\r\n");
      out.write("	</div><!-- //container -->\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- ========================= FOOTER END // ========================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
